# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt
    - name: Lint with pylint
      run: |
        pylint tests/ 2>&1 > pylint_report.txt
    - name: Upload pylint output file
      uses: actions/upload-artifact@v2
      with:
        name: pylint_report
        path: pylint_report.txt
    - name: Test with coverage
      run: |
        coverage run --source=. -m unittest
        coverage report
        coverage html
    - name: Upload coverage output file
      uses: actions/upload-artifact@v2
      with:
        name: coverage_html
        path: htmlcov/
